### ISSUE TITLE
Having issues with multiple mower setup

### ISSUE THREAD

**Issue by ethanopp** [jeff-winn/homebridge-automower-platform#171]
**Describe Your Problem:**

I have 2 automowers now both connected with the OAuth flow. Front yard works fine, backyard does not. I also can control the backyard mower from the husqvarna app directly, so it does not seem to be an API (husqvarna server side) or cellular connection issue from the mower itself.

**Logs:**

```
An unexpected error occurred while attempting to set 'Schedule' for 'Backyard'. UnexpectedServerError: ERR: [404] {"errors":[{"id":"1583e0f6-52e4-49ac-a3bf-b2112aed61f4","status":"404","code":"no.mower.connection","title":"No mower connection","detail":"No connection between the cloud service and the mower product."}]}
    at DefaultErrorFactory.unexpectedServerError (/homebridge/node_modules/homebridge-automower-platform/dist/errors/errorFactory.js:29:16)
    at AutomowerClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:111:41)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'ERR0000'
}
```

**Plugin Config:**

```json
        {
            "name": "Automower Bridge",
            "lang": "en",
            "appKey": "xxxxx",
            "authentication_mode": "client_credentials",
            "application_secret": "xxxxx",
            "_bridge": {
                "username": "XX:00:C3:99:XX:XX",
                "port": 50721
            },
            "platform": "Homebridge Automower Platform"
        },
```

**Environment:**

* **Plugin Version**:
v1.3.0-rc2
* **Homebridge Version**: 
v1.5.1
* **Node.js Version**: 
v16.18.0
* **NPM Version**: 
v8.19.2
* **Operating System**: 
QNAP Linux Docker

**Comment by jeff-winn** [comment]
Do both mowers show up in HomeKit?

The only thing I can think of is that the mower is using the wrong mower id from the list of mowers that occurs on plugin startup. I never tested it with multiple mowers, so you might be the first one using it like this. Wouldn't surprise me if I had a bug lurking in there somewhere.

To enable debugging you can follow the instructions here: https://jeff-winn.github.io/homebridge-automower-platform/extras/debugging

Be advised, turning on debug logging *will* be outputting the Bearer tokens used to access your account. If you upload the logs here, make sure those tokens are removed or people can access your account.

You should be able to search the logs for the following message "api.mc.husqvarna.dev/v1/mowers" to find the request being used to pull your list of mowers.

For example:
<img src="https://user-images.githubusercontent.com/6961614/200047634-f7cb86a4-2830-4a1d-b272-872335657af4.png" width="50%" />

That id should be the same one sent in later requests when you have HomeKit send control commands (like turning schedule on or pausing the mower)

<img src="https://user-images.githubusercontent.com/6961614/200048427-9914ab32-d0ad-49ca-9da4-02bbc6e97205.png"  />

The response from those requests would likely be where that 404 you're seeing would occur.

**Comment by ethanopp** [comment]
I've been using it for a while and it was working fine for both - seems to just have happened once I switched over the client auth.. Both still showing in homebridge accessories.

Logs seem like the correct request is being made, using the correct mower id

`[11/4/2022, 2:59:00 PM] [Homebridge Automower Platform - Automower Bridge] Sending request [1/5]: XXXXX
 {"url":"https://api.amc.husqvarna.dev/v1/mowers/<correct id here>/actions","method":"POST","headers":{"X-Api-Key":"XXXXX","Content-Type":"application/vnd.api+json","Authorization":"Bearer XXXX.XXXX.XXXX-XXXX-XXX-XX-XXX-XX-XX-X-XXX-X-X-X","Authorization-Provider":"husqvarna"},"body":"{\"data\":{\"type\":\"ResumeSchedule\"}}"}
[11/4/2022, 2:59:15 PM] [Homebridge Automower Platform - Automower Bridge] Received response: XXXX
 {"status":404,"statusText":"Not Found","body":{"errors":[{"id":"03234751-10bc-43b2-ae11-23ca55bf513a","status":"404","code":"no.mower.connection","title":"No mower connection","detail":"No connection between the cloud service and the mower product."}]}}
[11/4/2022, 2:59:15 PM] [Homebridge Automower Platform - Automower Bridge] An unexpected error occurred while attempting to set 'Schedule' for 'Backyard'. UnexpectedServerError: ERR: [404] {"errors":[{"id":"03234751-10bc-43b2-ae11-23ca55bf513a","status":"404","code":"no.mower.connection","title":"No mower connection","detail":"No connection between the cloud service and the mower product."}]}
    at DefaultErrorFactory.unexpectedServerError (/homebridge/node_modules/homebridge-automower-platform/dist/errors/errorFactory.js:29:16)
    at AutomowerClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:111:41)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'ERR0000'
}`

...Interestingly enough, I just went back to my app now after I got this error and it is showing 'Blocked' with a timer for how long I need to wait to put in the pin code to unlock it...

Could the request that is being made cause it to do this?

...again front one still working fine

**Comment by ethanopp** [comment]
Also seeing this when i restart homebridge
`[11/4/2022, 3:34:31 PM] [Automower Bridge] An unexpected error occurred while shutting down the plugin. Error: ERR: 403 -> {"errors": [{"title": "Error in API Gateway","code": "INVALID_API_KEY"}]} 
    at AuthenticationClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:120:23)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/authenticationClient.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by ethanopp** [comment]
Also... keep alive stream seems to only be pinging with the first mower's ID.. not sure it matters

**Comment by jeff-winn** [comment]
It's strange that it was working and then stopped like that. If you switch back to the Password auth mode that you were using previously does the plugin resume working normally?

**Comment by jeff-winn** [comment]
Also, I was just reviewing their documentation on the website to see if I missed anything. The scopes definitely weren't provided, but none of their samples passed them along either, but other documentation indicated they were required.

Going to pass them along as requested by the documentation rather than the samples to see if that has any impact. Should be able to push another RC release here in a few minutes.

**Comment by ethanopp** [comment]
Still getting issues with password authentication when trying to issue commands from the plugin
`[11/4/2022, 3:51:33 PM] [Homebridge Automower Platform - Automower Bridge] An unexpected error occurred while attempting to set 'Pause' for 'Backyard'. UnexpectedServerError: ERR: [404] {"errors":[{"id":"34d896e2-f87a-4dc4-af29-e1f1099fea3e","status":"404","code":"no.mower.connection","title":"No mower connection","detail":"No connection between the cloud service and the mower product."}]}
    at DefaultErrorFactory.unexpectedServerError (/homebridge/node_modules/homebridge-automower-platform/dist/errors/errorFactory.js:29:16)
    at AutomowerClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:111:41)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'ERR0000'
}`

**Comment by ethanopp** [comment]
Yes for months

**Comment by ethanopp** [comment]
...just downgraded to v1.2.2, still getting erros but just for my 2nd automower... very strange. Maybe something changed on their end? Hopefully passing the scopes resolves it

**Comment by jeff-winn** [comment]
Well at least it was working at some point, I'm looking over the changes recently for 1.3 right now trying to see if I botched anything in the code but nothing is jumping out at me.

**Comment by jeff-winn** [comment]
New version has been published to npm, you should see an update button shortly in the Homebridge UI.

**Comment by ethanopp** [comment]
Just pulled latest - front still works...same error on backyard

**Comment by jeff-winn** [comment]
Been thinking over here, and looking at the code changes between 1.2.2 and 1.3...

First, you might want to try uninstalling the plugin, going into the Homebridge Settings menu option. There's a spot toward the bottom for "Manage Cached Accessories" that will let you remove a single cached accessory. You should be able to find your mowers listed in there. If you delete them, and then reinstall the plugin I'm not sure if it'll help but it might be worth a shot. It'll just remove all your automations if you do this.

Second, there's also the option of giving me the logs (of which I'm not a fan since that puts you at risk). There could be some kind of data discrepancy in them when using client credentials flow with multiple mowers. I'd need the full logs, of which the only truely sensitive information is that Bearer token and your client credentials (which this can also have the secret recycled on Husqvarna's website if you are concerned). The Bearer token shows up repeatedly in the logs, whereas the login will only occur once on Homebridge startup.

Ideally you'd have the startup logs that gets the list of mowers, and one that performs an action on the mower.

**Comment by jeff-winn** [comment]
Also, I did submit a bug report to Husqvarna in case it is something on their end. I'm just hoping to rule out problems within my control before I throw it over the fence and hope they address it.

The password flow not working is fairly concerning that's for sure. Switching between them shouldn't cause any issues.

**Comment by jeff-winn** [comment]
Interesting, I just noticed the same problem randomly with my own mower. Perhaps it really is just an issue with Husqvarna right now in their cloud services.

```
[11/4/2022, 6:30:33 PM] [Homebridge Automower Platform] Sending request [1/5]: e937981a-caca-46d9-89e9-0c4de7071e8d
 {"url":"https://api.amc.husqvarna.dev/v1/mowers/REDACTED/actions","method":"POST","headers":{"X-Api-Key":"REDACTED","Content-Type":"application/vnd.api+json","Authorization":"Bearer REDACTED","Authorization-Provider":"husqvarna"},"body":"{\"data\":{\"type\":\"ParkUntilFurtherNotice\"}}"}
[11/4/2022, 6:30:33 PM] [Homebridge Automower Platform] Received response: e937981a-caca-46d9-89e9-0c4de7071e8d
 {"status":404,"statusText":"Not Found","body":{"errors":[{"id":"0a463bdc-8ccc-4ca4-b8bc-461b2bfdd74c","status":"404","code":"no.mower.connection","title":"No mower connection","detail":"No connection between the cloud service and the mower product."}]}}
[11/4/2022, 6:30:33 PM] [Homebridge Automower Platform] An unexpected error occurred while attempting to set 'Schedule' for 'Dobby'. UnexpectedServerError: ERR: [404] {"errors":[{"id":"0a463bdc-8ccc-4ca4-b8bc-461b2bfdd74c","status":"404","code":"no.mower.connection","title":"No mower connection","detail":"No connection between the cloud service and the mower product."}]}
    at DefaultErrorFactory.unexpectedServerError (/homebridge/node_modules/homebridge-automower-platform/dist/errors/errorFactory.js:29:16)
    at AutomowerClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:111:41)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'ERR0000'
}
```

I'll keep an eye on it here, but maybe check it in a few days and see if the problem persists.

**Comment by ethanopp** [comment]
Completely removed bridge from homekit, uninstalled plugin, removed all cached items, reinstalled.... still same issue... let me take a pass at pulling logs and replacing the... Disabling the plugin for a day or so to see if the 'blocking' issue is being caused by it

**Comment by ethanopp** [comment]
Seems like it might be something in the plugin that was causing that 'blocking' error... been running the mowers for past day or so with plugin disabled and they've been fine - also controllable from the auto-mower connect app

**Comment by jeff-winn** [comment]
That's really weird. My only guess would be that the Husqvarna app and the plugin are both using client credentials if you've got them both open at the same time they might be competing for credentials.

I haven't seen that at all on my end at all, maybe I'll see if I can replicate it here.

**Comment by ethanopp** [comment]
But arent they using their own credentials? I created a new app just for the plugin... also not sure how that would explain it only having issues with backyard mower and not front

**Comment by jeff-winn** [comment]
They should be using their own token yeah, but it’d depend on whether the two are competing for the “right” login token.

I can’t do it today, but I’ll see if I can get my own to get locked up somehow. Hopefully I don’t get locked out 🤣

**Comment by ethanopp** [comment]
Hah nah worst case scenario you just have to be around it for when the timer is up to put in the code, but theres only a short window to do so otherwise it locks again for longer

**Comment by jeff-winn** [comment]
Ok, so I did manage to get myself locked out by submitting WAYYYY to many login attempts until they finally blocked me.

Once that happened I noticed a few things:
- I could no longer sign in with my password based credentials either when using the app key created for my client credentials authentication mode.
- After reverting back to the original application key *78e47163-dd2a-48bf-9af9-3cec8cadae00* that was there previously with the password grant did start letting me login again.

I did this externally of the plugin by using the developer tools I work with, so the plugin was not the cause of my lock out. It was however impacted by it when I restarted my server. This likely should have also occurred after the token expired normally. Going to run another test in a minute with a new application id, break it, and then have my development version of the plugin running with a short token recycle and see what happens.

If a lockout does occur, it'd likely be caused by the timer running in the background used to keep the event stream alive.

**Comment by jeff-winn** [comment]
A few notes:

- Renewing the application secret for the existing locked out application id did **NOT** unlock the account.
- Using a different application id and secret together **DID** allow the account to be accessed.

![image](https://user-images.githubusercontent.com/6961614/200196428-cfe46e8b-7077-422e-a83f-256192aaccce.png)

With the lockout message being identical to the bad credentials message, I might change the response error just if anyone else sees it they don't think their credentials are wrong.

**Comment by jeff-winn** [comment]
Associated with #174

**Comment by ethanopp** [comment]
Did you ever get the 404 “No mower connection”? That one I don’t think had anything to do with the iOS app.
It seems like the error you were getting was an error against the “auth api” not the “connect” api they have when you add them to the app in their dev console

**Comment by jeff-winn** [comment]
I did yeah, one of my posts earlier had it pop up randomly that thankfully I grabbed the logs (and put them here) before they were overwritten, can't say that I've ever noticed it before. I do know that there's a couple spots on my property where the mower doesn't respond to inputs from either HomeKit or the Husqvarna mobile app. But that's just in that area, it responds otherwise. I doubt that's the issue you're having given what you've described.

You're probably safe to just switch your application key and use password flow for a while if it works better. Maybe Husqvarna will fix the issue with their APIs.

I do know that the mobile app and what I'm using for the plugin use different APIs provided by Husqvarna. The one I'm using is publicly available, I didn't want to try and hack into something used by their mobile app (which also is what causes the issue with connection sharing and unable to use them both).

**Comment by ethanopp** [comment]
You mean switch the key back to `78e47163-dd2a-48bf-9af9-3cec8cadae00`and use password flow? ...Tried that a few days ago and was still getting the error

**Comment by jeff-winn** [comment]
Yes, that was my suggestion. That shouldn’t cause a lockout unless your password is incorrect. That’s the original app I setup when I first released the software.

**Comment by ethanopp** [comment]
Yep started fresh and password auth seems to be working... will monitor for a few days and report back if any issues

**Comment by jeff-winn** [comment]
Sounds good, you're at risk for them just one day whacking the password login support and you can't login but you can always cross that bridge when it happens. If the dual mowers aren't working when client credentials aren't used, it's definitely not something in the code being wrong otherwise password wouldn't work either.

Apprecate you reporting the issue, it's at least good to know.

**Comment by jeff-winn** [comment]
So their service desk responded back and is disputing the mower connection (already told them their app worked).

Can you go pull the following log entries while you had client credentials setup? Also, make sure you leave the mower ids intact in both entries.

- The GET that pulled your list of mowers (only occurred once on startup). Should contain “/mowers” in the log with nothing else after it in the url.
- The POST command that was trying to drive the backyard mower. Should contain  “/action” in the log.

For that first call I mentioned, there should be a bunch of location entries on it for where the GPS says it was at, you’ll want to remove those too so you’re not effectively telling the Internet your home address.

Just asking for this preemptively so I have what I need when they ask for it. Thanks!

**Comment by jeff-winn** [comment]
They’ve asked for you to email them at 
“openapi.servicedesk@husqvarna.com”

You can mention Jeff and Johan were talking about this. My email was titled: ”BUG - Issues with multiple mowers and client credentials” and it the chain started on 11/4/2022 @ 9:30 PM Eastern US time zone. They should be able to find it from there.

Let me know what happens, or if I need to change anything on my end.

**Comment by jeff-winn** [comment]
Yeah i noticed that recently as well. It seems to only occur on startup when logging in and discovering the mowers.

I’m pretty sure Husqvarna changed policies recently that the 1 second between calls now also applies across their services.

Associated with #195

**Comment by ethanopp** [comment]
Does it not make calls for a 'keep alive' check?

They have been working fine for a few days now after startup...but sometimes when i go to manually control both (i.e. click my automower on scene which turns both schedule on at same time) i get the 429s

`[11/22/2022, 1:23:52 PM] [Homebridge Automower Platform] An unexpected error occurred while attempting to set 'Schedule' for 'Backyard'. UnexpectedServerError: ERR: [429] {"message":"Limit Exceeded"}
    at DefaultErrorFactory.unexpectedServerError (/homebridge/node_modules/homebridge-automower-platform/dist/errors/errorFactory.js:33:16)
    at AutomowerClientImpl.<anonymous> (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:115:41)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-automower-platform/dist/clients/automowerClient.js:5:58) {
  errorCode: 'ERR0000'
}`

**Comment by jeff-winn** [comment]
The keep alive check is just checking the state of the stream and doing local zombie detection when it saw events last. No web service calls occur outgoing during the check.

That last sentence you mentioned about using a scene to set both mowers would definitely cause an issue depending how long they took.

**Comment by jeff-winn** [comment]
The 429s finally appeared over here tonight around 10:00 PM EST. The issue is definitely not with the plug-in making too many calls between the login and get mowers on startup.

I threw a 60 second sleep in there to see if it’d have any impact and it did not. 

That would also explain why it has been fine for so long and now it’s seeing this. The Husqvarna web services must have rate limiting at AWS that’s global to the service and if the instance exceeds that rate limitation it begins rejecting everyone.

**Comment by ethanopp** [comment]
If that were the case though I would expect the app to not work either but it still was

**Comment by jeff-winn** [comment]
Their app uses different endpoints to handle the communication. I’m using their publicly available endpoints to communicate with them and not using their private undocumented web services to do it.

They likely have much higher tolerances on their app, whereas their public APIs likely do not.

**Comment by jeff-winn** [comment]
I got a response from Husqvarna support on the rate limiting problem, they said they found an issue with the quota calculation and will have a patch deployed Monday.

Yay!

**Comment by ethanopp** [comment]
Awesome sounds good!

**Comment by jeff-winn** [comment]
Did you ever get that problem worked out using when client credentials with Husqvarna?

**Comment by ethanopp** [comment]
I’ve been using the client credentials but then the 429 issue started…so hopefully by Monday if they fix it I can confirm that other issue is no longer occurring and we can close

**Comment by jeff-winn** [comment]
So you were able to get in touch with them about the issue? That's wonderful news! They did say that they increased everyones quotas in the mean time to reduce the 429s occurring on their web services.

I've got a patch upcoming (in the 1.4.0 release) to place a call rate limiter in the client used to communicate with Husqvarna as well. This should ensure if you have a scene set switches for both mowers that it does not exceed the call rates on the second mower and cause an issue.

**Comment by jeff-winn** [comment]
Just wanted to check in, are we good to close?

**Comment by ethanopp** [comment]
Yeah it seems to be working as of today...and I have to winterize this week anyway so hopefully we'll still be good by next season... thanks again!
