### ISSUE TITLE
Introduce support for Gardena mowers

### ISSUE THREAD

**Issue by jeff-winn** [jeff-winn/homebridge-automower-platform#245]
**Is your feature request related to a problem? Please describe:**

As a user, I would like to use a Gardena series mower with the plug-in.

**Describe the solution you'd like:**

Begin introducing support for the Gardena mowers in a preview form.

**Describe alternatives you've considered:**

Leaving the mower unsupported. Gone back and forth on this a few times, with everything in place it shouldn’t be much work to add it.

**Additional context:**

I will need help to do this as I won’t have the hardware required for Husqvarna to authorize access to the APIs. It seems you must have a Gardena product registered.

**Mower:**

* **Year**: 2016
* **Model**: Sileno Smart City 500

**Acceptance Criteria**
- [x] Gardena Smart mowers are discovered on startup
- [x] Turning the mower switch on causes the mower to mow the lawn
- [x] Turning the mower switch off causes the mower to park
- [x] While the mower is moving around the property the motion sensor indicates movement
- [x] When the mower is going home the arriving contact sensor is set
- [x] When the mower is leaving home the leaving contact sensor is set
- [x] When the mower encounters a fault, the motion sensor indicates faulted
- [x] When the mower has been tampered with, the motion sensor indicates tampered

**Comment by jeff-winn** [comment]
@GEDE35 any interest in helping with this?

**Comment by jeff-winn** [comment]
@cschildhorn any interest in helping with this?

**Comment by GEDE35** [comment]
@jeff-winn Hi. I would love to help. I have a Gardena Sileno Smart 500.

**Comment by cschildhorn** [comment]
Hi @jeff-winn I recently switched to Home Assistant. Sorry.

**Comment by jeff-winn** [comment]
@GEDE35 sorry for the delayed response, we got influenza yesterday. I’ll probably reach back out in a couple days once the virus has ran it’s course.

In the meantime it might be easier to handle the communication while we do this together on the Homebridge Discord.

https://discord.gg/homebridge-432663330281226270

Also, do you already have Homebridge installed? If not, you’ll want that as well.

**Comment by GEDE35** [comment]
@jeff-winn No worries. I just noticed that you specifically asked for someone who has a Gardena product registered. My mower is unfortunately not registered. I do still want to help if I can.

**Comment by jeff-winn** [comment]
Theoretically as long as you can control the mower from an app while you’re not at home it should be doable.

**Comment by GEDE35** [comment]
I can control it through the gardena app away from home, so that should be fine.
I found the homebridge discord. We can continue there.

**Comment by Barloew** [comment]
@jeff-winn I am interested in helping with this. 
I have a Gardena Smart gateway installed with a Gardena Sileno series mower registered to the account.
I am using Apple HomeKit and have an existing Homebridge already installed.
I have access to Postman for doing RESTful API calls.
I have a Discord account.
I am on Central European Time

**Comment by jeff-winn** [comment]
@Barloew awesome! I can always use some more testers to help with it. Here's an invite link to the Homebridge Discord, just add me as a friend on Discord (jeff-winn#6551) and we can get you going. We've been doing it over DMs due to the transferring log files for diagnostics as we add functionality.

https://discord.gg/homebridge-432663330281226270

**Comment by jeff-winn** [comment]
@Barloew i have been attempting to contact you, if still interested check your DMs on Discord 🙂

**Comment by jeff-winn** [comment]
After working with @GEDE35 for a few months and testing it for most of this summer, the plugin appears to be stable enough after the rework to publish.

Closing this as issue resolved.
