### ISSUE TITLE
An error occurred within the socket stream

### ISSUE THREAD

**Issue by CameronVIE** [jeff-winn/homebridge-automower-platform#350]
**Describe The Bug:**
Homebridge  - latest Version, Node.js 20.11.1 brings the error

[4/17/2024, 1:30:09 PM] [Husqvarna 315x] An error occurred within the socket stream, see the following for additional details:
 {
  error: undefined,
  message: 'Unexpected server response: 403',
  type: undefined
}

**To Reproduce:**
Every minute the same error

**Expected behavior:**
no error and successfully starting Automower 315x via Home

**Logs:**

[4/17/2024, 1:30:09 PM] [Husqvarna 315x] An error occurred within the socket stream, see the following for additional details:
 {
  error: undefined,
  message: 'Unexpected server response: 403',
  type: undefined
}

**Plugin Config:**

 {
            "name": "Husqvarna 315X",
            "device_type": "automower",
            "sensor_mode": "all",
            "lang": "en",
            "appKey": "xxxxxxxxxxxxxxxxxxxxxxxx",
            "authentication_mode": "client_credentials",
            "application_secret": "yyyyyyyyyyyyyyyyyyyyyyyyyyy",
            "platform": "Homebridge Automower Platform"
        }

**Screenshots:**

![grafik](https://github.com/jeff-winn/homebridge-automower-platform/assets/62641314/3f3a371f-dce2-400c-a0c9-eef506c8e9eb)

**Mower:**

* **Year**: 2018
* **Model**: Automower 315X
* 
**Environment:**

* **Plugin Version**: v2.1.0 
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.11.1
* **Operating System**: Ubuntu 20.04.05 LTS

**Comment by CameronVIE** [comment]
Removed all former content for automower-plugin from json file and created new settings via plugin. Now it works.

**Comment by CameronVIE** [comment]
Removed all former content for automower-plugin from json file and created new settings via plugin. Now it works.

**Comment by jeff-winn** [comment]
> Removed all former content for automower-plugin from json file and created new settings via plugin. Now it works.

Just curious, what do you think the problem was? Sometimes those 403s occur because people forget to add the APIs to their account in the developer portal.

**Comment by CameronVIE** [comment]
Hello Jeff! I really dont know. For me it was the fact, that i removed anything from  my former configuration with password. Restarted homebridge and configured it from scratch. INFO: I had from the beginning both apis enabled in developer portal!

**Comment by tobeehh** [comment]
Still the same Problem, even after doing what the cameron and jeff said. APIs and everything activated.
