### ISSUE TITLE
Mower State "RESTRICTED" reported as State.FAULTED

### ISSUE THREAD

**Issue by MichelRabozee** [jeff-winn/homebridge-automower-platform#356]
**Describe The Bug:**
I think there is a wrong interpretation of the "RESTRICTED" state reported for an Automower. The automowerMowerStateConverter consider the State.RESTRICTED as reported by Husqvarna as being a model.State.FAULTED.

However, the Husqvarna developer documentation ( https://developer.husqvarnagroup.cloud/apis/automower-connect-api?tab=status%20description%20and%20error%20codes ) says that "RESTRICTED" means that "Mower can currently not mow due to week calender, or override park", so it is not a fault, but a normal state when in the charge station, waiting for the next schedule to start.

**To Reproduce:**
I ran into that because I saw in the Homebridge log that everytime the mower is in the charging station waiting for the next scheduled run, it is interpreted as a "GENERAL_FAULT".

**Expected behavior:**
The State.RESTRICTED should be handled in the conversion code as for instance State.WAIT_POWER_UP, so returning a model.State.UNKNOWN. That will lead to a "NO FAULT" status when the mower is waiting for the next scheduled run insteead of a GENERAL_FAULT status.

**Logs:**

```
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Arriving Sensor' for 'Mickey': CLOSED
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Leaving Sensor' for 'Mickey': CLOSED
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Motion Sensor' for 'Mickey': GENERAL_FAULT
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Motion Sensor' for 'Mickey': NOT_TAMPERED
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Motion Sensor' for 'Mickey': NO_MOTION
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Schedule' for 'Mickey': ON
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Cutting Height' for 'Mickey': 5
[07/08/2024, 18:03:49] [Corniche Automower] Changed 'Pause' for 'Mickey': OFF
```

**Plugin Config:**

**Screenshots:**

**Mower:**

* **Year**: 2016
* **Model**: Automower 420

**Environment:**

* **Plugin Version**: 2.2
* **Homebridge Version**: v1.8.4
* **Node.js Version**:  v20.10.0
* **Operating System**: macOS / hb-service

**Comment by jeff-winn** [comment]
Thanks for reporting it, I haven't used the on-board scheduler in quite a while so I didn't notice the issue.

I was able to replicate it by using the Husqvarna app to disable the schedule for today, and saw the fault come in immediately afterward.
```
[8/7/2024, 6:58:20 PM] [Homebridge Automower Platform] Received event:
 {"id":"REDACTED","type":"status-event","attributes":{"battery":{"batteryPercent":82},"mower":{"mode":"MAIN_AREA","activity":"PARKED_IN_CS","state":"RESTRICTED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":1723075200000,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"WEEK_SCHEDULE"},"metadata":{"connected":true,"statusTimestamp":1723071500034}}}
[8/7/2024, 6:58:20 PM] [Homebridge Automower Platform] Changed 'Motion Sensor' for 'Dobby': GENERAL_FAULT
[8/7/2024, 6:58:20 PM] [Homebridge Automower Platform] Changed 'Schedule' for 'Dobby': OFF
```

**Comment by MichelRabozee** [comment]
You are welcome :-)

BTW, I did some additions in order to add the "Alarm sensor" I spoke about in my previous enhancement-suggestion post. However, I am not skilled enough to create a PR :-( I only touched 4 files (locales/de.json, locales/en.json, src/mowerAccessory.ts, src/mowerAccessoryFactory.ts) and added 2 others (services/alarmSensor.ts, services/policies/mowerInAlarmPolicy.ts), as well as the fix for the RESTRICTED (services/husqvarna/automower/converters/automowerMowerStateConverter.ts), I include them in a zip file if interested. With that, you can get a notification using Home(kit) only.

[AlarmSensor.zip](https://github.com/user-attachments/files/16538891/AlarmSensor.zip)

**Comment by jeff-winn** [comment]
@MichelRabozee I appreciate the offer, however it was a little more complicated than just marking it as unknown. The sensors and switches drive off those values, which is why the converter is in place to divine what's actually going on with the mower based on the state data that was received.

**Comment by MichelRabozee** [comment]
Thank you ! Seems nice.

In fact, I found a case where the mower state should be seen as FAULTED: when mowing in the secondary area, when the battery runs off, and the on-board scheduler is active, the activity becomes STOPPED_IN_GARDEN and the state is RESTRICTED. This should be seen as the mower homekit state being FAULTED in order to notify the user that the battery is depleted and the mower needs to be returned manually to its charging station.

**Comment by jeff-winn** [comment]
I won’t be able to replicate that one, so I’m going to need the JSON of the status event that came in. If you’re reading the states you might already have it.

Sometimes they use error code in conjunction with the fault codes.

**Comment by MichelRabozee** [comment]
Sure, I will provide that... Can you point me on how to capture it (I cheated to get the ACTIVITY and STATE by editing the .js file and add some log.info...). I guess there is some logging to activate ?

(Also, it should not matter if in secondary zone or primary... Having activity STOPPED_IN_GARDEN is a fault if in state RESTRICTED (it won't be able to start again, it requires manual handling - it may happen, for instance when battery gets old and need replacement... sometimes it does not handle the level well and may not be able to go back to charging station).

**Comment by jeff-winn** [comment]
Here’s the link to the instructions:
https://jeff-winn.github.io/homebridge-automower-platform/extras/debugging

**Comment by MichelRabozee** [comment]
I started moving the secondary area; let's wait till battery depletion (in general, 3-4 hours... I replaced the battery a month ago, bthe previous one, 8 years old, lasted less than 30 minutes...

I come back when I have everything.

**Comment by MichelRabozee** [comment]
Sure, I am preparing a documented message with all the actions I made for you to follow. I will lift the mower as well.

**Comment by MichelRabozee** [comment]
Here it is:

Taking the mower out of charging station to bring it to secondary area:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":100},"mower":{"mode":"MAIN_AREA","activity":"UNKNOWN","state":"STOPPED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":1723449600000,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723298403168}}}
```
[10/08/2024, 16:00:03] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': GENERAL_FAULT


Mower mowing in the secondary area:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":99},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723298437963}}}
```
[10/08/2024, 16:00:38] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NO_FAULT
[10/08/2024, 16:00:38] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': MOTION_DETECTED

Still mowing in secondary area:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":93},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723299280685}}}
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":87},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723300120850}}}
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":81},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723300960777}}}
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":75},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723301801016}}}
```

Lift up when mowing in secondary area:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":69},"mower":{"mode":"SECONDARY_AREA","activity":"NOT_APPLICABLE","state":"FATAL_ERROR","inactiveReason":"NONE","errorCode":12,"errorCodeTimestamp":1720083317000},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723302584143}}}
```
[10/08/2024, 17:09:44] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': GENERAL_FAULT
[10/08/2024, 17:09:44] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NO_MOTION

REMARK:
Strange, error code says 12 "Empty battery", should have been 14 "Mower lifted" or 15 "Lifted". Battery is at 69 % anyway...


Press STOP enter code:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":69},"mower":{"mode":"SECONDARY_AREA","activity":"UNKNOWN","state":"STOPPED","inactiveReason":"NONE","errorCode":12,"errorCodeTimestamp":1720083317000},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723302593722}}}
```
[10/08/2024, 17:09:53] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NO_FAULT
[10/08/2024, 17:09:53] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': TAMPERED


Resume mowing secondary area:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":69},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723302607431}}}
```
[10/08/2024, 17:10:07] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NOT_TAMPERED
[10/08/2024, 17:10:07] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': MOTION_DETECTED


Still mowing in secondary area:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":62},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723303450833}}}
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":56},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723304290851}}}
```
(...)
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723313931770}}}
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"SECONDARY_AREA","activity":"MOWING","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723314771635}}}
```


Battery depleted:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"SECONDARY_AREA","activity":"NOT_APPLICABLE","state":"PAUSED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723315112510}}}
```
[10/08/2024, 20:38:32] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NO_MOTION
[10/08/2024, 20:38:32] [Corniche Automower] Changed 'Pause' for 'Paolina': ON
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"SECONDARY_AREA","activity":"STOPPED_IN_GARDEN","state":"RESTRICTED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723315116994}}}
```
[10/08/2024, 20:38:37] [Corniche Automower] The value 'STOPPED_IN_GARDEN' is not supported.
[10/08/2024, 20:38:37] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NO_FAULT
[10/08/2024, 20:38:37] [Corniche Automower] Changed 'Pause' for 'Paolina': OFF
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"SECONDARY_AREA","activity":"STOPPED_IN_GARDEN","state":"RESTRICTED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723315119808}}}
```


Putting the mower back to the charging station:
```json
 {"id":"**REDACTED**","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"MAIN_AREA","activity":"PARKED_IN_CS","state":"RESTRICTED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":1723449600000,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"WEEK_SCHEDULE"},"metadata":{"connected":true,"statusTimestamp":1723316060055}}}
```

**Comment by jeff-winn** [comment]
Yeah, that's the same sort of things I've seen from Husqvarna regarding their documentation versus what the mowers actually signal out of themselves. It's likely mower specific as well for a particular model/year depending on how the firmware works internally.

I suppose I could just stop signaling out tampered, in the end you're probably gonna have to walk over to it regardless whether it's been lifted or whether it's ran out of battery. It'd be a more consistent experience from the plugin at least and reduce the chance of me having to interpret product specific error code differences between models.

**Comment by jeff-winn** [comment]
Taking a bit longer since I"m also adding support for out of battery detection. Mine is a 2020 so still fairly new. I haven't had any battery issues yet, other than when it can't find home.

**Comment by jeff-winn** [comment]
@MichelRabozee v2.3.0-preview.99 has been published. It should deal with the battery issue as well to fault when it runs out.

**Comment by MichelRabozee** [comment]
Thank you, I will test that next Tuesday.
I was intrigued yesterday during the mowing for testing battery depletion: the battery was reported at 0% at some point, but the mower still ran for a good 30 minutes. Besides a 0% level the events continued to report normal mowing (and it was mowing indeed). So the battery level is not really accurate, only the event saying it is STOPPED_IN_GARDEN is accurate.

**Comment by jeff-winn** [comment]
Fair point, the issue I noticed was the pause switch turning on when fully depleted and not it faulting as it should have.

I’ll have to see what mine does when it runs next. Might have to adjust the logic slightly.

**Comment by MichelRabozee** [comment]
Yeah, I saw that as well, but it was quite transient (5 seconds), so the Motion sensor reacted with NO_MOTION then GENERAL_FAULT. For me, it is OK:

[10/08/2024, 20:38:32] [Corniche Automower] Received event:
```json
 {"id":"aa8bd1aa-0b39-43af-8f47-a74e22832173","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"SECONDARY_AREA","activity":"NOT_APPLICABLE","state":"PAUSED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723315112510}}}
````
[10/08/2024, 20:38:32] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NO_MOTION

[10/08/2024, 20:38:37] [Corniche Automower] Received event:
```json
 {"id":"aa8bd1aa-0b39-43af-8f47-a74e22832173","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"SECONDARY_AREA","activity":"STOPPED_IN_GARDEN","state":"RESTRICTED","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723315116994}}}
```
[10/08/2024, 20:38:37] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': GENERAL_FAULT

For the battery level issue, I modified temporarily like this, leaving out the battery level, and only focusing on STOPPED_IN_GARDEN:
//        if (attributes.battery.batteryPercent === 0) {
//            return model.State.FAULTED; // The battery has been depleted, and will need intervention to fix.
//        }
//
//        if (attributes.mower.mode === Mode.SECONDARY_AREA && attributes.mower.activity === Activity.STOPPED_IN_GARDEN) {
//            return model.State.FAULTED;
//        }

        if (attributes.mower.activity === Activity.STOPPED_IN_GARDEN) {
            return model.State.FAULTED; // The battery has been depleted, and will need intervention to fix.
        }

Let's see what it does next Tuesday :-)

**Comment by jeff-winn** [comment]
I blocked the charge station earlier today to see how mine would react. Here's the results I saw:
```log
[8/12/2024, 1:45:50 PM] [Homebridge Automower Platform] Received event:
 {"id":"REDACTED","type":"status-event","attributes":{"battery":{"batteryPercent":2},"mower":{"mode":"MAIN_AREA","activity":"GOING_HOME","state":"IN_OPERATION","inactiveReason":"NONE","errorCode":11,"errorCodeTimestamp":1723469311000},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723484750630}}}
[8/12/2024, 1:49:30 PM] [Homebridge Automower Platform] Received event:
 {"id":"REDACTED","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"MAIN_AREA","activity":"NOT_APPLICABLE","state":"FATAL_ERROR","inactiveReason":"NONE","errorCode":0,"errorCodeTimestamp":0},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723484969984}}}
[8/12/2024, 1:49:30 PM] [Homebridge Automower Platform] Changed 'Motion Sensor' for 'Dobby': GENERAL_FAULT
[8/12/2024, 1:49:30 PM] [Homebridge Automower Platform] Changed 'Motion Sensor' for 'Dobby': NO_MOTION
[8/12/2024, 1:49:30 PM] [Homebridge Automower Platform] Changed 'Schedule' for 'Dobby': OFF
[8/12/2024, 1:49:31 PM] [Homebridge Automower Platform] Received event:
 {"id":"REDACTED","type":"status-event","attributes":{"battery":{"batteryPercent":0},"mower":{"mode":"MAIN_AREA","activity":"NOT_APPLICABLE","state":"FATAL_ERROR","inactiveReason":"NONE","errorCode":12,"errorCodeTimestamp":1723469531000},"planner":{"nextStartTimestamp":0,"override":{"action":"NOT_ACTIVE"},"restrictedReason":"NOT_APPLICABLE"},"metadata":{"connected":true,"statusTimestamp":1723484970962}}}
```
It sent the low battery notification about 5 minutes before it was completely out of battery. Which, after it did signal empty battery it ended up faulted, but the codes used were different than what you saw with your slightly older model.

**Comment by jeff-winn** [comment]
Given both our mowers sent out fault signals when out of battery, I ended up just removing the logic trying to detect it.

**v2.3.0-preview.100** has been published.

**Comment by MichelRabozee** [comment]
Your mower sends clearly the codes matching the Husqvarna documentation.
So I guess the shop doing the yearly maintenance did not keep the firmware updated :-( and I have no way to do that myself.

I do not see "STOPPED_IN_GARDEN" in the MAIN_AREA case. But I think the new converter will clearly satisfy the behaviours of both our mowers :-)

I install that preview.100 now, so I will check tomorrow (Tuesdays and Thursdays are the days for the SECONDARY AREA).

**Comment by jeff-winn** [comment]
Sounds good, let me know how it goes

**Comment by MichelRabozee** [comment]
Hello,

works like a charm!

[13/08/2024, 13:30:56] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': NO_MOTION
[13/08/2024, 13:30:56] [Corniche Automower] Changed 'Pause' for 'Paolina': ON
[13/08/2024, 13:31:04] [Corniche Automower] Changed 'Motion Sensor' for 'Paolina': GENERAL_FAULT
[13/08/2024, 13:31:04] [Corniche Automower] Changed 'Pause' for 'Paolina': OFF

(
and my personal addition to have an extra "Alarm Sensor" in order to have a simple Homekit notification on fault works too !
[13/08/2024, 13:31:04] [Corniche Automower] Changed 'Alarm Sensor' for 'Paolina': GENERAL_FAULT
[13/08/2024, 13:31:04] [Corniche Automower] Changed 'Alarm Sensor' for 'Paolina': ALARM_DETECTED
)

All is well and instantaneous thanks to events ! Thank you !

**Comment by jeff-winn** [comment]
Glad you found something that’d work for you. I’ll put a bit more thought into whether I want to do sensor checkboxes in the configs. 

Everyone seems to have lots of contention there which ones they want. Perhaps just saying here’s which ones the plug-in provides and pick what you want is good enough.

Appreciate all the help!

**Comment by MichelRabozee** [comment]
The pleasure is mine ! Thanks to you !

(if it is not too much difficult/too much work, yes, a way to pick the sensors you want activated is a way to meet anyone needs).
